"""archive table

Revision ID: 5dca50b23567
Revises: 
Create Date: 2023-06-17 07:52:07.023335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dca50b23567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_archived', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_event', schema=None) as batch_op:
        batch_op.drop_column('date_archived')

    # ### end Alembic commands ###
