"""empty message

Revision ID: 94641372a8e8
Revises: cfa15639d82c
Create Date: 2023-06-17 00:19:01.454165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94641372a8e8'
down_revision = 'cfa15639d82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
