"""Add address field to Directory

Revision ID: a4a2d092e04a
Revises: 
Create Date: 2023-06-21 15:11:47.035089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a2d092e04a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directory', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
