"""guest-list-update

Revision ID: aae087cd548b
Revises: e523b6ed985e
Create Date: 2023-06-16 11:16:21.905111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae087cd548b'
down_revision = 'e523b6ed985e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_budget_items_event_id', 'events', ['event_id'], ['id'])

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_title', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('zip', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('rsvp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('guests', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')
        batch_op.drop_column('rsvp')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('guest_title')

    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
