"""Add target_budget column to events table

Revision ID: b27d00785dd7
Revises: ef843bb3b7e3
Create Date: 2023-06-15 15:18:35.948695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27d00785dd7'
down_revision = 'ef843bb3b7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('target_budget')

    # ### end Alembic commands ###
