"""Update Guest model for self-referential relationship

Revision ID: d007d1d3c7c8
Revises: 
Create Date: 2023-06-22 13:12:14.512416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd007d1d3c7c8'
down_revision = None
branch_labels = None
depends_on = None

# Define a name for the constraint
constraint_name = "fk_guests_parent_id_guests_id"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(constraint_name, 'guests', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
