"""empty message

Revision ID: e523b6ed985e
Revises: b27d00785dd7
Create Date: 2023-06-15 15:22:42.418257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e523b6ed985e'
down_revision = 'b27d00785dd7'
branch_labels = None
depends_on = None


def upgrade():
    # Drop the temporary table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_budget_items")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
