"""Add budget_amount column to events table

Revision ID: ef843bb3b7e3
Revises: f74ed9d1cb8c
Create Date: 2023-06-15 12:35:54.436960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef843bb3b7e3'
down_revision = 'f74ed9d1cb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('budget_amount')

    # ### end Alembic commands ###
