"""Added name and type to Event

Revision ID: f74ed9d1cb8c
Revises: 
Create Date: 2023-06-14 15:35:56.499632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74ed9d1cb8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.drop_column('eventName')
        batch_op.drop_column('eventType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventType', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('eventName', sa.INTEGER(), nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
